// PROJECT
export const BEGIN_GET_PROJECTS = "BEGIN_GET_PROJECTS";
export const FAIL_GET_PROJECTS = "FAIL_GET_PROJECTS";
export const GET_PROJECTS = "GET_PROJECTS";
export const PROJECT_LAYOUT = 'PROJECT_LAYOUT';
export const PROJECT_ADD = 'PROJECT_ADD';
export const PROJECT_DELETE = 'PROJECT_DELETE';

// INTERFACE
export const INTERFACES_LIST = 'INTERFACES_LIST';
export const INTERFACES_LAYOUT = 'INTERFACES_LAYOUT';
export const BEGIN_GET_INTERFACES = 'BEGIN_GET_INTERFACES';
export const INTERFACE_SAVE_BEGIN = 'INTERFACE_SAVE_BEGIN';
export const INTERFACE_SAVE_DONE = 'INTERFACE_SAVE_DONE';
export const INTERFACE_DELETE_DONE = 'INTERFACE_DELETE_DONE';
export const INTERFACE_COPY_DONE = 'INTERFACE_COPY_DONE';
export const INTERFACE_URL_DONE = 'INTERFACE_URL_DONE';

//INTERFACE DETAILS
export const INTERFACE_BEGIN_GET = 'INTERFACE_BEGIN_GET';
export const INTERFACE_INFO = 'INTERFACE_INFO';
export const INTERFACE_REQUEST = 'INTERFACE_REQUEST';
export const INTERFACE_SCHEMA = 'INTERFACE_SCHEMA';
export const INTERFACE_TEMPLATE = 'INTERFACE_TEMPLATE';
